client:
    url: '*'
spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        password: password1
        url: jdbc:mariadb://localhost:3306/localdb
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
