openapi: 3.0.0
info:
  version: '1'
  title: 'ToDoMainService'
  license:
    name: MIT
servers:
  - url: 'localhost:8080'
paths:
  /tasks/create:
    post:
      summary: 'Creates new task'
      operationId: createTask
      tags:
        - task
      parameters: []
      responses:
        '200':
          description: 'Confirmation that a new task was created: Details about a task ID'
          headers:
            x-next:
              description: new task ID
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /tasks/read:
    post:
      summary: 'Retunrs a list with all tasks'
      operationId: readTasks
      tags:
        - task
      parameters: []
      responses:
        '200':
          description: 'List of tasks'
          headers:
            x-next:
              description: List of tasks
              schema:
                type: array
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /tasks/update:
    post:
      summary: 'Updates a specific task'
      operationId: readTasks
      tags:
        - task
      parameters:
        - name: id
          in: query
          description: task ID
          required: true
          schema:
            type: integer
            format: long
      responses:
        '200':
          description: 'Confirmation that a task was updated'
          headers:
            x-next:
              description: ID of updated task
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /tasks/delete:
    post:
      summary: 'Deletes a specific task'
      operationId: readTasks
      tags:
        - task
      parameters:
        - name: id
          in: query
          description: task ID
          required: true
          schema:
            type: integer
            format: long
      responses:
        '200':
          description: 'Confirmation that a task was deleted'
          headers:
            x-next:
              description: ID of deleted task
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Task:
      type: object
      required:
        - id
        - description
        - isDone
        - dateTime
      properties:
        id:
          type: integer
          format: long
        description:
          type: string
        isDone:
          type: boolean
        dateTime:
          type: string
          format: dateTime
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []